Using cpu device
tot num of params: 623067
[2024-02-17 14:09:35,741][absl][WARNING] - Cannot set velocity on Entity with no free joint.
Logging to /Users/sangbin/maze/outputs/2024-02-17/14-09-29/wandb/run-20240217_140933-r0co8i9z/files/r0co8i9z/PPO_1
---------------------------
| time/              |    |
|    fps             | 10 |
|    iterations      | 1  |
|    time_elapsed    | 5  |
|    total_timesteps | 64 |
---------------------------
Traceback (most recent call last):
  File "/Users/sangbin/maze/train_epn_3d.py", line 92, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/Users/sangbin/maze/train_epn_3d.py", line 79, in main
    model.learn(total_timesteps=cfg.optim.total_timesteps, callback=callback)
  File "/Users/sangbin/maze/ppo/epn/epn.py", line 509, in learn
    self.train()
  File "/Users/sangbin/maze/ppo/epn/epn.py", line 408, in train
    loss.backward()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
Exception ignored in atexit callback: <function ContextBase.__init__.<locals>._free_at_exit at 0x34249acb0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/base.py", line 59, in _free_at_exit
    self_weakref()._free_unconditionally()  # pylint: disable=protected-access
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
    self._render_executor.terminate(self._free_on_executor_thread)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/executor/render_executor.py", line 144, in terminate
    cleanup_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/base.py", line 104, in _free_on_executor_thread
    patient.free()
KeyboardInterrupt: